Repository woorifisa-projects/HaeDal-admin, pull requests merged in 2023-09, with the labels that each got.

#14 Feature : 관리자 로그 조회 기능 추가, 고객 삭제 로직 수정
  .idea/workspace.xml
  backend/src/main/java/dev/syntax/backend/admin/model/Admin.java
  backend/src/main/java/dev/syntax/backend/log/controller/LogController.java
  backend/src/main/java/dev/syntax/backend/log/dto/response/LogResponse.java
  backend/src/main/java/dev/syntax/backend/log/model/Log.java
  backend/src/main/java/dev/syntax/backend/log/model/LogType.java
  backend/src/main/java/dev/syntax/backend/log/repository/LogRepository.java
  backend/src/main/java/dev/syntax/backend/log/service/LogService.java
  backend/src/main/java/dev/syntax/backend/log/service/LogServiceImp.java
  backend/src/main/java/dev/syntax/backend/product/controller/ProductController.java
  backend/src/main/java/dev/syntax/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/dev/syntax/backend/user/controller/UserController.java
  backend/src/main/java/dev/syntax/backend/user/dto/response/AdminResponse.java
  backend/src/main/java/dev/syntax/backend/user/dto/response/UserResponse.java
  backend/src/main/java/dev/syntax/backend/user/model/User.java
  frontend/src/layouts/default/AppBar.vue
  frontend/src/router/index.js
  frontend/src/views/AdminLoginView.vue
  frontend/src/views/Header.vue
  frontend/src/views/LogManagement.vue
  frontend/src/views/ProductManagement.vue
  frontend/src/views/UserManagement.vue
Labels: 백엔드, 리팩토링, 프론트엔드

#16 Refactor : 관리자 로직 수정
  backend/src/main/java/dev/syntax/backend/log/model/Log.java
  backend/src/main/java/dev/syntax/backend/product/controller/ProductController.java
  backend/src/main/java/dev/syntax/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/dev/syntax/backend/product/model/Product.java
  backend/src/main/java/dev/syntax/backend/subscribe/model/Subscribe.java
  backend/src/main/java/dev/syntax/backend/subscribe/repository/SubscribeRepository.java
  backend/src/main/java/dev/syntax/backend/subscribe/service/SubscribeService.java
  backend/src/main/java/dev/syntax/backend/subscribe/service/SubscribeServiceImp.java
  backend/src/main/java/dev/syntax/backend/user/controller/UserController.java
  backend/src/main/java/dev/syntax/backend/user/dto/response/UserResponse.java
  backend/src/main/java/dev/syntax/backend/user/model/User.java
  frontend/index.html
  frontend/public/faviconHaeDal.ico
  frontend/src/layouts/default/AppBar.vue
  frontend/src/layouts/default/Default.vue
  frontend/src/layouts/default/Footer.vue
  frontend/src/layouts/default/View.vue
  frontend/src/views/EditProduct.vue
  frontend/src/views/EditUser.vue
  frontend/src/views/LogManagement.vue
  frontend/src/views/ProductManagement.vue
  frontend/src/views/UserManagement.vue
Labels: 백엔드, 리팩토링, 프론트엔드, UI

#18 style : 관리자 로고 변경
  frontend/src/assets/img/HaeDalLogo.png
  frontend/src/layouts/default/AppBar.vue
Labels: UI

#20 refactor : router 경로 변경 및 기본경로 로그인 페이지 설정
  backend/src/main/java/dev/syntax/backend/admin/controller/AdminController.java
  backend/src/main/java/dev/syntax/backend/log/controller/LogController.java
  backend/src/main/java/dev/syntax/backend/product/controller/ProductController.java
  backend/src/main/java/dev/syntax/backend/subscribe/controller/SubscribeController.java
  backend/src/main/java/dev/syntax/backend/user/controller/UserController.java
  frontend/src/layouts/default/AppBar.vue
  frontend/src/router/index.js
Labels: 리팩토링

#24 refactor : 경로 일부 수정함
  backend/src/main/java/dev/syntax/backend/admin/controller/AdminController.java
  backend/src/main/java/dev/syntax/backend/log/controller/LogController.java
  backend/src/main/java/dev/syntax/backend/product/controller/ProductController.java
  backend/src/main/java/dev/syntax/backend/subscribe/controller/SubscribeController.java
  backend/src/main/java/dev/syntax/backend/user/controller/UserController.java
  frontend/src/views/AddProduct.vue
  frontend/src/views/AdminLoginView.vue
  frontend/src/views/EditProduct.vue
  frontend/src/views/EditUser.vue
  frontend/src/views/LogManagement.vue
  frontend/src/views/ProductManagement.vue
  frontend/src/views/UserManagement.vue
Labels: 리팩토링

#28 refactor : 고객관리 탭 클릭시, 활성화된 고객들만 조회되도록 수정
  frontend/src/views/ProductManagement.vue
  frontend/src/views/UserManagement.vue
Labels: 리팩토링

#30 refactor: admin login페이지 전반적인 수정
  frontend/src/views/AdminLoginView.vue
Labels: 리팩토링, 프론트엔드

#32 fix : 추가시 상품 최대금액 적용 안되는 에러 해결
  frontend/src/views/AddProduct.vue
  frontend/src/views/EditProduct.vue
  frontend/src/views/EditUser.vue
Labels: 프론트엔드

#34 refactor: 상품추가 페이지 UI개선, 성능최적화 작업
  backend/src/main/java/dev/syntax/backend/log/controller/LogController.java
  backend/src/main/java/dev/syntax/backend/product/controller/ProductController.java
  backend/src/main/java/dev/syntax/backend/product/dto/response/ProductResponse.java
  backend/src/main/java/dev/syntax/backend/user/controller/UserController.java
  frontend/src/layouts/default/AppBar.vue
  frontend/src/views/AddProduct.vue
  frontend/src/views/AdminLoginView.vue
  frontend/src/views/EditProduct.vue
  frontend/src/views/EditUser.vue
  frontend/src/views/LogManagement.vue
  frontend/src/views/ProductManagement.vue
  frontend/src/views/UserManagement.vue
Labels: 리팩토링, 프론트엔드
